//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalData.DDoc.WebUI.Views.Viewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalData.DDoc.WebUI.Views.Viewer.Resources.ViewerResource", typeof(ViewerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuntos.
        /// </summary>
        public static string attachments_label {
            get {
                return ResourceManager.GetString("attachments_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar adjuntos.
        /// </summary>
        public static string attachments_title {
            get {
                return ResourceManager.GetString("attachments_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista actual.
        /// </summary>
        public static string bookmark_label {
            get {
                return ResourceManager.GetString("bookmark_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista actual (copiar o abrir en una nueva ventana).
        /// </summary>
        public static string bookmark_title {
            get {
                return ResourceManager.GetString("bookmark_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer archivo del documento.
        /// </summary>
        public static string ddoc_first_title {
            get {
                return ResourceManager.GetString("ddoc_first_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último archivo del documento.
        /// </summary>
        public static string ddoc_last_title {
            get {
                return ResourceManager.GetString("ddoc_last_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente archivo.
        /// </summary>
        public static string ddoc_next_title {
            get {
                return ResourceManager.GetString("ddoc_next_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo anterior.
        /// </summary>
        public static string ddoc_prev_title {
            get {
                return ResourceManager.GetString("ddoc_prev_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los documentos PDF no tienen permiso de usar sus propios colores: &apos;Permitir que las páginas elijan sus propios colores&apos; esta desactivada en el navegador..
        /// </summary>
        public static string document_colors_disabled {
            get {
                return ResourceManager.GetString("document_colors_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor:.
        /// </summary>
        public static string document_properties_author {
            get {
                return ResourceManager.GetString("document_properties_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string document_properties_close {
            get {
                return ResourceManager.GetString("document_properties_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de creación:.
        /// </summary>
        public static string document_properties_creation_date {
            get {
                return ResourceManager.GetString("document_properties_creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creador:.
        /// </summary>
        public static string document_properties_creator {
            get {
                return ResourceManager.GetString("document_properties_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string document_properties_date_string {
            get {
                return ResourceManager.GetString("document_properties_date_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del archivo:.
        /// </summary>
        public static string document_properties_file_name {
            get {
                return ResourceManager.GetString("document_properties_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del archivo:.
        /// </summary>
        public static string document_properties_file_size {
            get {
                return ResourceManager.GetString("document_properties_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB ({1} bytes).
        /// </summary>
        public static string document_properties_kb {
            get {
                return ResourceManager.GetString("document_properties_kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabras claves:.
        /// </summary>
        public static string document_properties_keywords {
            get {
                return ResourceManager.GetString("document_properties_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades del documento….
        /// </summary>
        public static string document_properties_label {
            get {
                return ResourceManager.GetString("document_properties_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB ({1} bytes).
        /// </summary>
        public static string document_properties_mb {
            get {
                return ResourceManager.GetString("document_properties_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de modificación:.
        /// </summary>
        public static string document_properties_modification_date {
            get {
                return ResourceManager.GetString("document_properties_modification_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de páginas:.
        /// </summary>
        public static string document_properties_page_count {
            get {
                return ResourceManager.GetString("document_properties_page_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productor PDF:.
        /// </summary>
        public static string document_properties_producer {
            get {
                return ResourceManager.GetString("document_properties_producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto:.
        /// </summary>
        public static string document_properties_subject {
            get {
                return ResourceManager.GetString("document_properties_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades del documento….
        /// </summary>
        public static string document_properties_title {
            get {
                return ResourceManager.GetString("document_properties_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título:.
        /// </summary>
        public static string document_properties_title1 {
            get {
                return ResourceManager.GetString("document_properties_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión PDF:.
        /// </summary>
        public static string document_properties_version {
            get {
                return ResourceManager.GetString("document_properties_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string download_label {
            get {
                return ResourceManager.GetString("download_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string download_title {
            get {
                return ResourceManager.GetString("download_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string error_close {
            get {
                return ResourceManager.GetString("error_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo: {0}.
        /// </summary>
        public static string error_file {
            get {
                return ResourceManager.GetString("error_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menos información.
        /// </summary>
        public static string error_less_info {
            get {
                return ResourceManager.GetString("error_less_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea: {0}.
        /// </summary>
        public static string error_line {
            get {
                return ResourceManager.GetString("error_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje: {0}.
        /// </summary>
        public static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más información.
        /// </summary>
        public static string error_more_info {
            get {
                return ResourceManager.GetString("error_more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pila: {0}.
        /// </summary>
        public static string error_stack {
            get {
                return ResourceManager.GetString("error_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.js v{0} (build: {1}).
        /// </summary>
        public static string error_version_info {
            get {
                return ResourceManager.GetString("error_version_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo:.
        /// </summary>
        public static string file_label {
            get {
                return ResourceManager.GetString("file_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de {0}.
        /// </summary>
        public static string file_of {
            get {
                return ResourceManager.GetString("file_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resaltar todo.
        /// </summary>
        public static string find_highlight_label {
            get {
                return ResourceManager.GetString("find_highlight_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrar:.
        /// </summary>
        public static string find_label {
            get {
                return ResourceManager.GetString("find_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coincidir con mayúsculas y minúsculas.
        /// </summary>
        public static string find_match_case_label {
            get {
                return ResourceManager.GetString("find_match_case_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string find_next_label {
            get {
                return ResourceManager.GetString("find_next_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la siguiente frase encontrada.
        /// </summary>
        public static string find_next_title {
            get {
                return ResourceManager.GetString("find_next_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la frase.
        /// </summary>
        public static string find_not_found {
            get {
                return ResourceManager.GetString("find_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string find_previous_label {
            get {
                return ResourceManager.GetString("find_previous_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la anterior frase encontrada.
        /// </summary>
        public static string find_previous_title {
            get {
                return ResourceManager.GetString("find_previous_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se alcanzó el final del documento, se buscará al inicio.
        /// </summary>
        public static string find_reached_bottom {
            get {
                return ResourceManager.GetString("find_reached_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se alcanzó el inicio del documento, se buscará al final.
        /// </summary>
        public static string find_reached_top {
            get {
                return ResourceManager.GetString("find_reached_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string findbar_label {
            get {
                return ResourceManager.GetString("findbar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar en el documento.
        /// </summary>
        public static string findbar_title {
            get {
                return ResourceManager.GetString("findbar_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la primera página.
        /// </summary>
        public static string first_page_label {
            get {
                return ResourceManager.GetString("first_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la primera página.
        /// </summary>
        public static string first_page_label1 {
            get {
                return ResourceManager.GetString("first_page_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la primera página.
        /// </summary>
        public static string first_page_title {
            get {
                return ResourceManager.GetString("first_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string goBack_title {
            get {
                return ResourceManager.GetString("goBack_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar herramienta mano.
        /// </summary>
        public static string hand_tool_disable_label {
            get {
                return ResourceManager.GetString("hand_tool_disable_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivar herramienta mano.
        /// </summary>
        public static string hand_tool_disable_title {
            get {
                return ResourceManager.GetString("hand_tool_disable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar herramienta mano.
        /// </summary>
        public static string hand_tool_enable_label {
            get {
                return ResourceManager.GetString("hand_tool_enable_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar herramienta mano.
        /// </summary>
        public static string hand_tool_enable_title {
            get {
                return ResourceManager.GetString("hand_tool_enable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo PDF invalido o dañado..
        /// </summary>
        public static string invalid_file_error {
            get {
                return ResourceManager.GetString("invalid_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la última página.
        /// </summary>
        public static string last_page_label {
            get {
                return ResourceManager.GetString("last_page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la última página.
        /// </summary>
        public static string last_page_label1 {
            get {
                return ResourceManager.GetString("last_page_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la última página.
        /// </summary>
        public static string last_page_title {
            get {
                return ResourceManager.GetString("last_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un error ocurrió al cargar el PDF..
        /// </summary>
        public static string loading_error {
            get {
                return ResourceManager.GetString("loading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string loading_error_indicator {
            get {
                return ResourceManager.GetString("loading_error_indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo PDF no encontrado..
        /// </summary>
        public static string missing_file_error {
            get {
                return ResourceManager.GetString("missing_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string next_label {
            get {
                return ResourceManager.GetString("next_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página siguiente.
        /// </summary>
        public static string next_title {
            get {
                return ResourceManager.GetString("next_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string open_file_label {
            get {
                return ResourceManager.GetString("open_file_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir archivo.
        /// </summary>
        public static string open_file_title {
            get {
                return ResourceManager.GetString("open_file_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquema del documento.
        /// </summary>
        public static string outline_label {
            get {
                return ResourceManager.GetString("outline_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar esquema del documento.
        /// </summary>
        public static string outline_title {
            get {
                return ResourceManager.GetString("outline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página:.
        /// </summary>
        public static string page_label {
            get {
                return ResourceManager.GetString("page_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de {0}.
        /// </summary>
        public static string page_of {
            get {
                return ResourceManager.GetString("page_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la izquierda.
        /// </summary>
        public static string page_rotate_ccw_label {
            get {
                return ResourceManager.GetString("page_rotate_ccw_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la izquierda.
        /// </summary>
        public static string page_rotate_ccw_label1 {
            get {
                return ResourceManager.GetString("page_rotate_ccw_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la izquierda.
        /// </summary>
        public static string page_rotate_ccw_title {
            get {
                return ResourceManager.GetString("page_rotate_ccw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la derecha.
        /// </summary>
        public static string page_rotate_cw_label {
            get {
                return ResourceManager.GetString("page_rotate_cw_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la derecha.
        /// </summary>
        public static string page_rotate_cw_label1 {
            get {
                return ResourceManager.GetString("page_rotate_cw_label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar a la derecha.
        /// </summary>
        public static string page_rotate_cw_title {
            get {
                return ResourceManager.GetString("page_rotate_cw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño real.
        /// </summary>
        public static string page_scale_actual {
            get {
                return ResourceManager.GetString("page_scale_actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom automático.
        /// </summary>
        public static string page_scale_auto {
            get {
                return ResourceManager.GetString("page_scale_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustar página.
        /// </summary>
        public static string page_scale_fit {
            get {
                return ResourceManager.GetString("page_scale_fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string page_scale_percent {
            get {
                return ResourceManager.GetString("page_scale_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho de página.
        /// </summary>
        public static string page_scale_width {
            get {
                return ResourceManager.GetString("page_scale_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string password_cancel {
            get {
                return ResourceManager.GetString("password_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida. Por favor intenta de nuevo..
        /// </summary>
        public static string password_invalid {
            get {
                return ResourceManager.GetString("password_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa la contraseña para abrir este archivo PDF..
        /// </summary>
        public static string password_label {
            get {
                return ResourceManager.GetString("password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string password_ok {
            get {
                return ResourceManager.GetString("password_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo presentación.
        /// </summary>
        public static string presentation_mode_label {
            get {
                return ResourceManager.GetString("presentation_mode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar al modo presentación.
        /// </summary>
        public static string presentation_mode_title {
            get {
                return ResourceManager.GetString("presentation_mode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string previous_label {
            get {
                return ResourceManager.GetString("previous_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página anterior.
        /// </summary>
        public static string previous_title {
            get {
                return ResourceManager.GetString("previous_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string print_label {
            get {
                return ResourceManager.GetString("print_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string print_title {
            get {
                return ResourceManager.GetString("print_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string printing_cancel {
            get {
                return ResourceManager.GetString("printing_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando el documento para la impresión....
        /// </summary>
        public static string printing_label {
            get {
                return ResourceManager.GetString("printing_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: El PDF no cargo completamente para impresión..
        /// </summary>
        public static string printing_not_ready {
            get {
                return ResourceManager.GetString("printing_not_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: La impresión no esta completamente soportada por este navegador..
        /// </summary>
        public static string printing_not_supported {
            get {
                return ResourceManager.GetString("printing_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un error ocurrió al renderizar la página..
        /// </summary>
        public static string rendering_error {
            get {
                return ResourceManager.GetString("rendering_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} anotación].
        /// </summary>
        public static string text_annotation_type_alt {
            get {
                return ResourceManager.GetString("text_annotation_type_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniatura de la página {0}.
        /// </summary>
        public static string thumb_page_canvas {
            get {
                return ResourceManager.GetString("thumb_page_canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página {0}.
        /// </summary>
        public static string thumb_page_title {
            get {
                return ResourceManager.GetString("thumb_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miniaturas.
        /// </summary>
        public static string thumbs_label {
            get {
                return ResourceManager.GetString("thumbs_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar miniaturas.
        /// </summary>
        public static string thumbs_title {
            get {
                return ResourceManager.GetString("thumbs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar barra lateral.
        /// </summary>
        public static string toggle_sidebar_label {
            get {
                return ResourceManager.GetString("toggle_sidebar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar barra lateral.
        /// </summary>
        public static string toggle_sidebar_title {
            get {
                return ResourceManager.GetString("toggle_sidebar_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        public static string tools_label {
            get {
                return ResourceManager.GetString("tools_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        public static string tools_title {
            get {
                return ResourceManager.GetString("tools_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta inesperada del servidor..
        /// </summary>
        public static string unexpected_response_error {
            get {
                return ResourceManager.GetString("unexpected_response_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fuentes web están desactivadas: es imposible usar las fuentes PDF embebidas..
        /// </summary>
        public static string web_fonts_disabled {
            get {
                return ResourceManager.GetString("web_fonts_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumentar.
        /// </summary>
        public static string zoom_in_label {
            get {
                return ResourceManager.GetString("zoom_in_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aumentar.
        /// </summary>
        public static string zoom_in_title {
            get {
                return ResourceManager.GetString("zoom_in_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducir.
        /// </summary>
        public static string zoom_out_label {
            get {
                return ResourceManager.GetString("zoom_out_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducir.
        /// </summary>
        public static string zoom_out_title {
            get {
                return ResourceManager.GetString("zoom_out_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string zoom_title {
            get {
                return ResourceManager.GetString("zoom_title", resourceCulture);
            }
        }
    }
}
